(ASTNode (ASTLetDatum "x")
  (ASTNode (ASTSimpleDatum "plus")
    (ASTNode (ASTSimpleDatum "num")
      (ASTNode (ASTSimpleDatum "2") EmptyAST EmptyAST) EmptyAST)
    (ASTNode (ASTLetDatum "y")
      (ASTNode (ASTSimpleDatum "num")
        (ASTNode (ASTSimpleDatum "2") EmptyAST EmptyAST) EmptyAST)
      (ASTNode (ASTSimpleDatum "times")
        (ASTNode (ASTSimpleDatum "num")
          (ASTNode (ASTSimpleDatum "3") EmptyAST EmptyAST) EmptyAST)
        (ASTNode (ASTSimpleDatum "y") EmptyAST EmptyAST))))
  (ASTNode (ASTSimpleDatum "plus")
    (ASTNode (ASTSimpleDatum "x") EmptyAST EmptyAST)
    (ASTNode (ASTLetDatum "z")
      (ASTNode (ASTSimpleDatum "plus")
        (ASTNode (ASTSimpleDatum "x") EmptyAST EmptyAST)
        (ASTNode (ASTSimpleDatum "num")
          (ASTNode (ASTSimpleDatum "2") EmptyAST EmptyAST) EmptyAST))
      (ASTNode (ASTSimpleDatum "times")
        (ASTNode (ASTSimpleDatum "x") EmptyAST EmptyAST)
        (ASTNode (ASTSimpleDatum "z") EmptyAST EmptyAST))))),
